### ISSUE TITLE
Does not build with Python 3.7

### ISSUE THREAD

**Issue by wom-bat** [grisha/mod_python#79]
Get:
<code>
mod_python.c: In function ‘python_init’:
mod_python.c:750:22: warning: format ‘%s’ expects argument of type ‘char *’, but argument 8 has type ‘wchar_t *’ {aka ‘int *’} [-Wformat=]
  750 |                      "python_init: Python executable found '%s'.",
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  751 |                      Py_GetProgramFullPath());
</code>
and
`_apachemodule.c:856:5: error: too few arguments to function ‘_PyImport_FixupExtensionObject’
  856 |     _PyImport_FixupExtensionObject(m, name, name);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.7m/Python.h:145,
                 from /usr/src/mod_python/src/include/mod_python.h:46,
                 from _apachemodule.c:25:
/usr/include/python3.7m/import.h:117:17: note: declared here
  117 | PyAPI_FUNC(int) _PyImport_FixupExtensionObject(PyObject*, PyObject *,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`

**Comment by grisha** [comment]
Thank you for reporting this - if you so solve it, please share your patch via a PR, it might be a while before I have time to look into this.

**Comment by NickWinston123** [comment]
I am having this problem with python 3.10, I don't know if I am doing anything wrong 

`_apachemodule.c: In function ‘_apache_module_init’:
_apachemodule.c:854:5: error: too few arguments to function ‘_PyImport_FixupExtensionObject’
     _PyImport_FixupExtensionObject(m, name, name);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.10/import.h:91:0,
                 from /usr/include/python3.10/Python.h:134,
                 from /home/noah/mod_python/src/include/mod_python.h:46,
                 from _apachemodule.c:25:
/usr/include/python3.10/cpython/import.h:24:17: note: declared here
 PyAPI_FUNC(int) _PyImport_FixupExtensionObject(PyObject*, PyObject *,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
apxs:Error: Command failed with rc=65536
.
Makefile:54: recipe for target 'mod_python.so' failed
make[1]: *** [mod_python.so] Error 1
make[1]: Leaving directory '/home/noah/mod_python/src'
Makefile:34: recipe for target 'do_dso' failed
make: *** [do_dso] Error 2`
